---
language: ruby

bundler_args: --without system_tests development

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4" $RUBYGEMS_VERSION="2.7.8"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6"

notifications:
  email: false
