name    'ghoneycutt-inittab'
version '2.1.2'
source 'git://github.com/ghoneycutt/puppet-module-inittab.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manages inittab'
description 'Manages inittab'
project_page 'https://github.com/ghoneycutt/puppet-module-inittab'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
